vim.cmd("highlight clear")
vim.cmd("syntax reset")

vim.g.colors_name = "dustyrose"

vim.api.nvim_set_hl(0, "Normal", { fg = "#c8c0d0", bg = "#1a1b2a" })

vim.api.nvim_set_hl(0, "Comment", { fg = "#6e606a", italic = true })
vim.api.nvim_set_hl(0, "Constant", { fg = "#d8b888" })
vim.api.nvim_set_hl(0, "String", { fg = "#8cc080" })
vim.api.nvim_set_hl(0, "Character", { fg = "#8cc080" })
vim.api.nvim_set_hl(0, "Number", { fg = "#d8b888" })
vim.api.nvim_set_hl(0, "Boolean", { fg = "#e8a0b0" })
vim.api.nvim_set_hl(0, "Float", { fg = "#d8b888" })
vim.api.nvim_set_hl(0, "Identifier", { fg = "#d08890" })
vim.api.nvim_set_hl(0, "Function", { fg = "#e8a0b0" })
vim.api.nvim_set_hl(0, "Statement", { fg = "#b86878" })
vim.api.nvim_set_hl(0, "Conditional", { fg = "#b86878" })
vim.api.nvim_set_hl(0, "Repeat", { fg = "#b86878" })
vim.api.nvim_set_hl(0, "Label", { fg = "#d08890" })
vim.api.nvim_set_hl(0, "Operator", { fg = "#80b8d0" })
vim.api.nvim_set_hl(0, "Keyword", { fg = "#b86878" })
vim.api.nvim_set_hl(0, "Exception", { fg = "#d08890" })
vim.api.nvim_set_hl(0, "PreProc", { fg = "#b8a0d0" })
vim.api.nvim_set_hl(0, "Include", { fg = "#b86878" })
vim.api.nvim_set_hl(0, "Define", { fg = "#b86878" })
vim.api.nvim_set_hl(0, "Type", { fg = "#b8a0d0" })
vim.api.nvim_set_hl(0, "Structure", { fg = "#b8a0d0" })
vim.api.nvim_set_hl(0, "Typedef", { fg = "#b8a0d0" })
vim.api.nvim_set_hl(0, "Special", { fg = "#7890a0" })
vim.api.nvim_set_hl(0, "SpecialChar", { fg = "#7890a0" })
vim.api.nvim_set_hl(0, "Tag", { fg = "#d08890" })
vim.api.nvim_set_hl(0, "Delimiter", { fg = "#c8c0d0" })
vim.api.nvim_set_hl(0, "Debug", { fg = "#d08890" })
vim.api.nvim_set_hl(0, "Underlined", { fg = "#e8a0b0", underline = true })
vim.api.nvim_set_hl(0, "Error", { fg = "#d08890", bold = true })
vim.api.nvim_set_hl(0, "Todo", { fg = "#d8b888", bold = true })
vim.api.nvim_set_hl(0, "LineNr", { fg = "#3e3848" })
vim.api.nvim_set_hl(0, "CursorLine", { fg = "#c8c0d0" })
vim.api.nvim_set_hl(0, "Visual", { fg = "#c8c0d0" })
vim.api.nvim_set_hl(0, "Search", { fg = "#c8c0d0" })
vim.api.nvim_set_hl(0, "StatusLine", { fg = "#c8c0d0" })
vim.api.nvim_set_hl(0, "Pmenu", { fg = "#c8c0d0" })
vim.api.nvim_set_hl(0, "PmenuSel", { fg = "#c8c0d0" })
vim.api.nvim_set_hl(0, "DiffAdd", { fg = "#8cc080" })
vim.api.nvim_set_hl(0, "DiffChange", { fg = "#80b8d0" })
vim.api.nvim_set_hl(0, "DiffDelete", { fg = "#d08890" })
vim.api.nvim_set_hl(0, "SignColumn", { fg = "#c8c0d0" })
vim.api.nvim_set_hl(0, "ColorColumn", { fg = "#c8c0d0" })
vim.api.nvim_set_hl(0, "VertSplit", { fg = "#3e3848" })
vim.api.nvim_set_hl(0, "MatchParen", { fg = "#e8a0b0", bold = true })
