[tools]
fd = "latest"
fzf = "latest"
go = "latest"
neovim = "latest"
node = "latest"
opencode = "latest"
python = "latest"
rust = "latest"
starship = "latest"
zig = "0.15"
zoxide = "latest"
yazi = "latest"
lazygit = "latest"
pi = "latest"
ripgrep = "latest"
