[tools]
fd = "latest"
fzf = "latest"
go = "latest"
neovim = "latest"
node = "latest"
python = "latest"
rust = "latest"
starship = "latest"
zoxide = "latest"
yazi = "latest"
lazygit = "latest"
pi = "latest"
ripgrep = "latest"
tree-sitter = "latest"
tmux = "latest"
