preload = /home/luke/Pictures/wallpapers/wallpaper.jpg
splash = false

wallpaper {
    monitor = DP-4
    path = /home/luke/Pictures/wallpapers/wallpaper.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = /home/luke/Pictures/wallpapers/wallpaper.jpg
    fit_mode = cover
}
