[colors]
foreground = "#cdcdcd"
background = "#090909"
cursor_bg = "#cdcdcd"
cursor_fg = "#090909"
cursor_border = "#cdcdcd"
selection_fg = "#cdcdcd"
selection_bg = "#252530"
scrollbar_thumb = "#252530"
split = "#252530"

ansi = [
  "#252530", # black
  "#d8647e", # red
  "#7fa563", # green
  "#f3be7c", # yellow
  "#6e94b2", # blue
  "#bb9dbd", # magenta
  "#aeaed1", # cyan
  "#cdcdcd", # white
]

brights = [
  "#606079", # bright_black
  "#e08398", # bright_red
  "#99b782", # bright_green
  "#f5cb96", # bright_yellow
  "#8ba9c1", # bright_blue
  "#c9b1ca", # bright_magenta
  "#bebeda", # bright_cyan
  "#d7d7d7", # bright_white
]

[colors.tab_bar]
background = "#141415"
inactive_tab_edge = "#252530"

[colors.tab_bar.active_tab]
bg_color = "#252530"
fg_color = "#cdcdcd"
intensity = "Normal"
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#141415"
fg_color = "#606079"
intensity = "Normal"
underline = "None"
italic = false
strikethrough = false

[colors.tab_bar.inactive_tab_hover]
bg_color = "#252530"
fg_color = "#cdcdcd"
italic = false

[colors.tab_bar.new_tab]
bg_color = "#141415"
fg_color = "#6e94b2"

[colors.tab_bar.new_tab_hover]
bg_color = "#252530"
fg_color = "#8ba9c1"
italic = false
